INSERT INTO PUBLIC.USERS (USER_NAME,EMAIL,LOGIN,BIRTHDAY)
SELECT 'Maurice Padberg','Lucious36@hotmail.com','jmpyei3yET','1991-12-05'
WHERE NOT EXISTS
   (SELECT 1 FROM USERS WHERE EMAIL = 'Lucious36@hotmail.com');

MERGE INTO PUBLIC.MPA_RATINGS T
USING (
    SELECT 1 as id, 'G' as name UNION ALL
    SELECT 2, 'PG' UNION ALL
    SELECT 3, 'PG-13' UNION ALL
    SELECT 4, 'R' UNION ALL
    SELECT 5, 'NC-17'
) S
ON T.MPA_RATING_ID = S.id
WHEN NOT MATCHED THEN
INSERT (MPA_RATING_ID, MPA_RATING_NAME)
VALUES (S.id, S.name);

MERGE INTO PUBLIC.GENRES T
USING (
    SELECT 1 as id, 'Комедия' as name UNION ALL
    SELECT 2, 'Драма' UNION ALL
    SELECT 3, 'Мультфильм' UNION ALL
    SELECT 4, 'Триллер' UNION ALL
    SELECT 5, 'Документальный' UNION ALL
    SELECT 6, 'Боевик'
) S
ON T.GENRE_ID = S.id
WHEN NOT MATCHED THEN
INSERT (GENRE_ID, GENRE_NAME)
VALUES (S.id, S.name);

INSERT INTO PUBLIC.FILMS (FILM_NAME,DESCRIPTION,RELEASE_DATE,DURATION,MPA_RATING_ID)
SELECT 'zgBfnebudkkvw2k','jqNsZ5o49plCvU2YFhfK8Yedq1w0GBRfzapywyvCOtjWOguQOz','1962-02-07',96,1
WHERE NOT EXISTS
   (SELECT 1 FROM FILMS WHERE FILM_NAME = 'zgBfnebudkkvw2k');
