MERGE INTO PUBLIC.MPA_RATINGS T
USING (
    SELECT 1 as id, 'G' as name UNION ALL
    SELECT 2, 'PG' UNION ALL
    SELECT 3, 'PG-13' UNION ALL
    SELECT 4, 'R' UNION ALL
    SELECT 5, 'NC-17'
) S
ON T.MPA_RATING_ID = S.id
WHEN NOT MATCHED THEN
INSERT (MPA_RATING_ID, MPA_RATING_NAME)
VALUES (S.id, S.name);

MERGE INTO PUBLIC.GENRES T
USING (
    SELECT 1 as id, 'Комедия' as name UNION ALL
    SELECT 2, 'Драма' UNION ALL
    SELECT 3, 'Мультфильм' UNION ALL
    SELECT 4, 'Триллер' UNION ALL
    SELECT 5, 'Документальный' UNION ALL
    SELECT 6, 'Боевик'
) S
ON T.GENRE_ID = S.id
WHEN NOT MATCHED THEN
INSERT (GENRE_ID, GENRE_NAME)
VALUES (S.id, S.name);
